# Generated by Django 2.2.5 on 2019-09-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('networking', 'Networking'), ('food-drink', 'Food/Drink'), ('market', 'Market')], default='concert', max_length=100),
        ),
    ]
