# Generated by Django 2.2.3 on 2019-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190916_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('networking', 'Networking'), ('food-drink', 'Food/Drink'), ('market', 'Market')], default='concert', max_length=20),
        ),
    ]
